// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/1005281342/kratosdemouser/internal/biz"
	"github.com/1005281342/kratosdemouser/internal/conf"
	"github.com/1005281342/kratosdemouser/internal/data"
	"github.com/1005281342/kratosdemouser/internal/server"
	"github.com/1005281342/kratosdemouser/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	kratosDemoUserRepo := data.NewKratosDemoUserRepo(dataData, logger)
	kratosDemoUserUsecase := biz.NewKratosDemoUserUsecase(kratosDemoUserRepo, logger)
	kratosDemoUserService := service.NewKratosDemoUserService(kratosDemoUserUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, kratosDemoUserService, logger)
	grpcServer := server.NewGRPCServer(confServer, kratosDemoUserService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
