// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.0.1

package kratosdemouser

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type KratosDemoUserHTTPServer interface {
	Ping(context.Context, *PingReq) (*PingRsp, error)
}

func RegisterKratosDemoUserHTTPServer(s *http.Server, srv KratosDemoUserHTTPServer) {
	r := s.Route("/")
	r.GET("/ping/{msg}", _KratosDemoUser_Ping0_HTTP_Handler(srv))
}

func _KratosDemoUser_Ping0_HTTP_Handler(srv KratosDemoUserHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PingReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.kratosdemouser.KratosDemoUser/Ping")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Ping(ctx, req.(*PingReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PingRsp)
		return ctx.Result(200, reply)
	}
}

type KratosDemoUserHTTPClient interface {
	Ping(ctx context.Context, req *PingReq, opts ...http.CallOption) (rsp *PingRsp, err error)
}

type KratosDemoUserHTTPClientImpl struct {
	cc *http.Client
}

func NewKratosDemoUserHTTPClient(client *http.Client) KratosDemoUserHTTPClient {
	return &KratosDemoUserHTTPClientImpl{client}
}

func (c *KratosDemoUserHTTPClientImpl) Ping(ctx context.Context, in *PingReq, opts ...http.CallOption) (*PingRsp, error) {
	var out PingRsp
	pattern := "/ping/{msg}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.kratosdemouser.KratosDemoUser/Ping"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
